### ISSUE TITLE
TypeError: array_keys(): Argument #1 ($array) must be of type array, bool given

### ISSUE THREAD

**Issue by twisted1919** [voku/portable-utf8#108]
#### What is this feature about (expected vs actual behaviour)?
We expect to not get an error, instead we get:  
```
2021/06/18 13:40:25 [error] [exception.TypeError] [x] TypeError: array_keys(): Argument #1 ($array) must be of type array, bool given in /home/x/public_html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php:2344
Stack trace:
#0 /home/x/public_html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php(2344): array_keys()
#1 /home/x/public_html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php(5320): voku\helper\UTF8::fix_simple_utf8()
#2 /home/x/public_html/vendor/voku/anti-xss/src/voku/helper/AntiXSS.php(606): voku\helper\UTF8::rawurldecode()
#3 /home/x/public_html/vendor/voku/anti-xss/src/voku/helper/AntiXSS.php(651): voku\helper\AntiXSS->_decode_string()
#4 /home/x/public_html/vendor/voku/anti-xss/src/voku/helper/AntiXSS.php(2050): voku\helper\AntiXSS->_do()
#5 /home/x/public_html/apps/common/components/utils/IOFilter.php(113): voku\helper\AntiXSS->xss_clean()
```
#### How can I reproduce it?  
It's difficult for us to say how since we get this on a production system and not on the dev system.  

#### Does it take minutes, hours or days to fix?
Minutes.  

#### Any additional information?
None.

**Comment by voku** [comment]
already fixed since 18 Oct 2021
